language: java

jdk:
  - openjdk7

before_install:
  - sudo apt-get -qq install lzop liblzo2-dev
  - git clone git://github.com/twitter/hadoop-lzo.git
  - cd hadoop-lzo
  - ant compile-native
  - mv build/native/Linux-* ../hadoop-lzo-native
  - cd ..
  - ls -l $PWD/hadoop-lzo-native
  - false

script: mvn test -Dtest.library.path=$PWD/hadoop-lzo-native/lib -Densure.lzo.tests=true

